version: "2"
services:

  mw-ui:
    image: openlmis/dev-ui:9.0.0
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - cce-ui
      - ui-components
      - ui-layout
      - dhis2-integration-ui
    depends_on:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - cce-ui
      - ui-components
      - ui-layout
      - dhis2-integration-ui

  auth-ui:
    image: openlmis/auth-ui:6.2.0
    volumes:
      - '/openlmis-auth-ui'

  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.0.3
    volumes:
      - '/openlmis-fulfillment-ui'

  referencedata-ui:
    image: openlmis/referencedata-ui:5.5.1
    volumes:
      - '/openlmis-referencedata-ui'

  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.0.3
    volumes:
      - '/openlmis-stockmanagement-ui'

  cce-ui:
    image: openlmis/cce-ui:1.0.3
    volumes:
     - '/openlmis-cce-ui'

  report-ui:
    image: openlmis/report-ui:5.2.0
    volumes:
      - '/openlmis-report-ui'

  requisition-ui:
    image: openlmis/requisition-ui:6.0.0
    volumes:
      - '/openlmis-requisition-ui'

  ui-components:
    image: openlmis/ui-components:7.1.0
    volumes:
      - '/openlmis-ui-components'

  ui-layout:
    image: openlmis/ui-layout:5.1.3
    volumes:
      - '/openlmis-ui-layout'

  dhis2-integration-ui:
    image: openlmismw/dhis2-integration-ui:1.0.0-SNAPSHOT
    volumes:
      - '/dhis2-integration-ui'

  image:
    build: .
    image: openlmismw/ui
